cookie:
  expiry_days: 30
  key: my_key
  name: my_cookie
credentials:
  usernames:
    iraitz:
      email: iraitzazka@gmail.com
      name: Iraitz
      password: $2b$12$ggRg9KN9P4K6yLFKaEtqUe3Q9B4D7P9iMvDp4B9KJvWcBXog6iq5K